// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: silence_job_grpc_service.proto

// Protobuf Java Version: 3.25.3
package com.old.silence.job.common.grpc.auto;

public interface GrpcSilenceJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcSilenceJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>.Metadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.Metadata metadata = 2;</code>
   * @return The metadata.
   */
  com.old.silence.job.common.grpc.auto.Metadata getMetadata();
  /**
   * <code>.Metadata metadata = 2;</code>
   */
  com.old.silence.job.common.grpc.auto.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
