// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: silence_job_grpc_service.proto

// Protobuf Java Version: 3.25.1
package com.old.silence.job.common.grpc.auto;

public final class SilenceJobGrpcService {
  private SilenceJobGrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcSilenceJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcSilenceJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036silence_job_grpc_service.proto\"p\n\010Meta" +
      "data\022\013\n\003uri\030\003 \001(\t\022\'\n\007headers\030\007 \003(\0132\026.Met" +
      "adata.HeadersEntry\032.\n\014HeadersEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"Q\n\025GrpcSilenc" +
      "eJobRequest\022\r\n\005reqId\030\001 \001(\003\022\033\n\010metadata\030\002" +
      " \001(\0132\t.Metadata\022\014\n\004body\030\003 \001(\t\"J\n\nGrpcRes" +
      "ult\022\r\n\005reqId\030\001 \001(\003\022\016\n\006status\030\002 \001(\005\022\017\n\007me" +
      "ssage\030\003 \001(\t\022\014\n\004data\030\004 \001(\tB(\n$com.old.sil" +
      "ence.job.common.grpc.autoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_descriptor,
        new java.lang.String[] { "Uri", "Headers", });
    internal_static_Metadata_HeadersEntry_descriptor =
      internal_static_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_Metadata_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GrpcSilenceJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrpcSilenceJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcSilenceJobRequest_descriptor,
        new java.lang.String[] { "ReqId", "Metadata", "Body", });
    internal_static_GrpcResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GrpcResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcResult_descriptor,
        new java.lang.String[] { "ReqId", "Status", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
